<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your ZIP code_zipcodemeded-0</name>
   <tag></tag>
   <elementGuidId>a0c958c1-df77-4844-9a52-05906195fc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipcodemeded-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipcodemeded-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92ecaa88-68f4-4069-b6d8-6ef4a0d6e002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>zipcodemeded-0</value>
      <webElementGuid>b783df54-6d7f-4aca-9b63-e8c8984335fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>204f40fc-0d4b-4e58-bd4a-62c381e12eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>buttonEnter(this,event)</value>
      <webElementGuid>b71a82b5-500a-4f0c-b5fc-0f3a558b82ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>storePartialZipEntry(this)</value>
      <webElementGuid>cbbd7cbf-f265-4a28-b353-f9bc93e0fda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validate(event), typeof event_formSubmit != 'undefined' &amp;&amp; event_formSubmit(event)</value>
      <webElementGuid>0d209886-e232-4acd-a7ee-ca6175790dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zip-input zip--horizontal f775602_feature_toggle_new</value>
      <webElementGuid>070ff1d2-e532-446e-bd15-f1191848a4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0c77fb7f-e006-4faa-90a9-70b91a64ff48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>0daa9928-c9dd-4426-b236-157383438521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcodemeded-0</value>
      <webElementGuid>a1d66dcf-bf7d-4441-bf18-d664d06f3305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipcodemeded-0</value>
      <webElementGuid>796b1648-74ef-4807-8399-337d09506796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code</value>
      <webElementGuid>6acf2b67-be76-490a-b453-1863b61e5dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f829c6c8-a9d1-4552-8729-6c36ff271266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zipcompindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c9293890-444b-43a9-892d-0284e8813a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipcodemeded-0&quot;)</value>
      <webElementGuid>c0935530-b446-4c10-9e20-49ed130c3797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipcodemeded-0']</value>
      <webElementGuid>e31f953f-326c-4ed0-90ed-bea2bbf0884b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalContentIdForSkipLink']/div[2]/div/div/div[2]/div/div[3]/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>01a116c8-57dd-4938-9589-0eb26015b2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>bc6c3ad4-b00e-4def-8d86-10fad77435d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'zipcodemeded-0' and @id = 'zipcodemeded-0' and @placeholder = 'Enter ZIP code']</value>
      <webElementGuid>3dfef2cd-56f5-4839-8044-f097fc5d803e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
